### ISSUE TITLE
Missing /sa_library/multi_fit_c.py

### ISSUE THREAD

**Issue by mikigom** [ZhuangLab/storm-analysis#18]
I see that ```/sa_library/multi_fit_c.py``` is need to use ```/simulator/astigmaticPSF.py```.
But there is ```/sa_library/multi_fit.c```, but ```/sa_library/multi_fit_c.py``` is not. Is this simply an error, an intent, or is it going to be implemented?

**Comment by HazenBabcock** [comment]
Thanks for reporting this. It is a mistake, `/sa_library/multi_fit_c.py` was renamed to `/sa_library/dao_fit_c.py` but this module was never updated. It should be fixed now.

**Comment by mikigom** [comment]
Thank you for your comment :)
