### ISSUE TITLE
Getting number of frames for drift correction when .dax file cannot be found

### ISSUE THREAD

**Issue by evanheller** [ZhuangLab/storm-analysis#20]
During drift correction, sa_library/i3togrid.py, getFilmSize() will not get the correct number of frames if the corresponding .dax file cannot be found because of lazy-loading. In this scenario, readinsight3.getNumberFrames() may need to be used instead so that the drift correction is calculated over the entire movie.

**Comment by HazenBabcock** [comment]
Unfortunately this is still a sub-optimal solution as the analysis still won't know the x and y dimensions of the movie and will just assume that it is 256 x 256. If you expect the movie to get separated from the analysis I'd suggest:

(1) Include the "append_metadata" parameter in your analysis XML file. When this is "1" then the analysis will include metadata in the localization data binary file (only the mlist.bin file currently). This data includes important things like the dimensions of the movie that the analysis comes from.

(2) Make a dummy .dax file. For this purpose the file does not actually have to contain any data, it just has to have the correct dimensions for the movie in the .inf file.

At some point I plan to make "append_metadata" the default, but right now this parameter is still experimental.

And even further in the future we'd drop this custom binary format and use a standard binary format like the micro-manager tagged spot format file, if that manages to get traction in the SMLM field.

**Comment by HazenBabcock** [comment]
I've converted the project to use HDF5 for the localization files. These include the key attributes such as the movie width, height and number of frames so this should no longer be an issue.
