### ISSUE TITLE
Change localization binary format.

### ISSUE THREAD

**Issue by HazenBabcock** [ZhuangLab/storm-analysis#29]
The current localization file format is too limiting, particularly for multi-plane data.

Requirements:
1. Binary (text files will be too large I think).
2. Extensible (adding new fields does not break everything).
3. Portable across different operating systems.
4. Standardized?

I think this is most likely going to be HDF5 as I think this is a better solution than protocol buffers, but suggestions are welcome!

**Comment by HazenBabcock** [comment]
This is mostly done now. I used HDF5 and the h5py library. 

Missing pieces include the clustering and the FRC code.

I took advantage of this opportunity to remove the double transpose. Older versions were transposing the movies and then transposing the localization coordinates. This is gone now and the localization coordinates should be the same as before. However some things are different such as the splines and sCMOS calibration data files, and they will need to be updated.

**Comment by cleterrier** [comment]
Hi Hazen,
Any plan to have a release using this new format? I have started to test storm-analysis (the latest Dec 22, 2017 release) and I'd be interested in this. Or would you suggest to build directly from the latest source code? I'm not sure how to use scons in an python 3 Anaconda virtual environment.

**Comment by HazenBabcock** [comment]
Hi Christophe,

I was planning on updating the clustering code first, but I've gotten side-tracked and I don't think that will happen in the next few months.

You can get wheels of latest version from Appveyor, [here](https://ci.appveyor.com/project/HazenBabcock/storm-analysis). Click on the job with the appropriate PYVERSION, then click on “ARTIFACTS”.

Also scons should just work now in a Python 3 Anaconda environment as scons has been updated to Python 3. I'll update the documentation for this soon.

**Comment by HazenBabcock** [comment]
Change complete and released..

**Comment by cleterrier** [comment]
Great news, will test ASAP. Thanks for letting me know. Now I have to learn this jupyter thing...
