### ISSUE TITLE
subprocess.call() environment 

### ISSUE THREAD

**Issue by aschrader5** [ZhuangLab/storm-analysis#37]
On Windows systems subprocess.call() is not setting the environment correctly, so many of the examples could fail if run in a virtual environment. This was found when setting up the project using the instructions found on the https://storm-analysis.readthedocs.io/en/stable/install.html website using a custom conda environment.

**Comment by aschrader5** [comment]
Good afternoon,


So I have just installed storm-analysis on a different computer, and it seems like the example is working. Without editing that line of code.


However I did get an error from the CMOS simulator.


Any way, both computers are running windows 10. The errors I was getting where along those lines.

I am using the Anaconda prompt for installation. I thought I went through the whole install process, but I might not have (?)


Since I do have other python installs, the python path variable has paths to some other modules (such as labjackpython).


I am also using python 2.7. I can get back to you on Thursday with more information if you need it.


Thank you again for your help,

Alex


Alex Schrader
Chemistry Graduate Student
Han Lab
Office 36 RAL

________________________________

**Comment by HazenBabcock** [comment]
I think the best thing is to just stop using subprocess.call() so much. I'll start removing this from the project.

**Comment by HazenBabcock** [comment]
The project no longer uses subprocess.call().
