### ISSUE TITLE
explanation of output columns and reference

### ISSUE THREAD

**Issue by hirschmichael** [ZhuangLab/storm-analysis#40]
I've tried to run your code and it worked! :sunglasses: :+1: 

I've looked at the output and I couldn't find any explanation for the columns: 

```index | frame | background | category | error | height | iterations | significance | sum | x | xsigma | y```

Could you add a description to the documentation (and meanwhile post it in a comment)?

Could you also add a reference that can be cited?

**Comment by HazenBabcock** [comment]
This is the output from `sa_utilities.hdf5_to_txt`?

The description of the columns is [here](https://storm-analysis.readthedocs.io/en/latest/output_files.html), it is the same as for XX.hdf5 output files.

What to cite depends on what analysis you used. Based on the columns it looks like you are using 3D-DAOSTORM? In that case the reference would be the 3D-DAOSTORM paper, "A high-density 3D localization algorithm for stochastic optical reconstruction microscopy", Optical Nanoscopy, 2012. This [README](https://github.com/ZhuangLab/storm-analysis/tree/master/storm_analysis) has the references for the different parts of the project.

**Comment by hirschmichael** [comment]
> This is the output from sa_utilities.hdf5_to_txt?

Yes. 

I was looking at the link of the github README, where it says "latest release", http://storm-analysis.readthedocs.io/en/stable/ :smile: 

For my point of view the issue is resolved. Not sure if you want to improve the README

Thanks.

**Comment by HazenBabcock** [comment]
I created a new release, so now "latest release" has the updated documentation.
