### ISSUE TITLE
How to render multi-color 2D/3D image

### ISSUE THREAD

**Issue by Ikru488** [ZhuangLab/storm-analysis#41]
For 2 channel movies, how can I display the final super-resolution image in 2 colors ?

**Comment by HazenBabcock** [comment]
You can use the `render2DImage()` or `render3DImage()` functions in `hdf5_to_image` to render each channel, then combine the channels into a RGB image using `numpy` or save the images for each channel separately and combine using imagej.

**Comment by Ikru488** [comment]
Ok, thanks !
