### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by xwyan1230** [ZhuangLab/storm-analysis#46]
Hi, I'm learning this STORM analysis and just started with the ipythonNotebook examples. For all the examples, every time it tries to do: 
import storm_analysis.sa_library.sa_h5py as saH5Py
there will be an error saying: 
dlopen(.../opt/anaconda3/lib/python3.8/site-packages/storm_analysis-2.2-py3.8.egg/storm_analysis/c_libraries/libgrid.dylib, 6): image not found
I wonder if there's any missing images for this example or am I supposed to give it some images for it to work?
Thank you in advance!

**Comment by HazenBabcock** [comment]
What I think your computer is trying to tell you is that it can't find the C library "libgrid.dylib". If a library by that name exists in the location being searched (../opt/anaconda3/..etc..), then it might in turn be that a dependency of this C library is missing.

**Comment by xwyan1230** [comment]
Thank you for your prompt reply! I installed both fftw and lapack as indicated on the initial page. Is this libgrid.dylib some library belongs to these two packages or generated during the script? Do you know where ipythonNotebook try to source for the c library (my installed c packages are under /usr/local/Cellar)? Sorry that I don't have any experience with c and thank you so much for your time!

**Comment by evanheller** [comment]
I think libgrid is part of `storm_analysis/sa_library`, and is supposed to be built when you run `python setup.py build_c` prior to installing storm_analysis with `python setup.py install`. I wonder if you forgot those two steps before trying out the iPython notebooks? Check to see if it exists in `storm_analysis/c_libraries` in your source tree first, and then perhaps in `/opt/anaconda3/lib/python3.8/site-packages/storm_analysis-2.2-py3.8.egg/storm_analysis/c_libraries/` (or wherever your site_packages is located).

**Comment by xwyan1230** [comment]
@evanheller Oh yes!! I just found the complete documentation and yes I didn't run the build_c before trying to setup the project. Thank you so much! I reinstalled everything and it is working now! Thank you for both of your time! @HazenBabcock
