### ISSUE TITLE
Cannot install; scons errors

### ISSUE THREAD

**Issue by MembraneEnzymology** [ZhuangLab/storm-analysis#47]
We currently cannot install the storm analysis package on our Ubuntu machine

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

After installing all the necessary dependencies and cloning the git repository we get the following error :

~/storm-analysis# python setup.py build_c
running build_c
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `storm_analysis/c_libraries/ft_math.o' is up to date.
scons: `storm_analysis/c_libraries/libadmm_lasso.so' is up to date.
scons: `storm_analysis/c_libraries/kdtree.o' is up to date.
scons: `storm_analysis/c_libraries/libdbscan.so' is up to date.
scons: `storm_analysis/c_libraries/libdensestorm.so' is up to date.
scons: `storm_analysis/c_libraries/libfista_fft.so' is up to date.
scons: `storm_analysis/c_libraries/libfrc.so' is up to date.
scons: `storm_analysis/c_libraries/homotopy_common.o' is up to date.
scons: `storm_analysis/c_libraries/homotopy_imagea.o' is up to date.
scons: `storm_analysis/c_libraries/homotopy_imagea_common.o' is up to date.
scons: `storm_analysis/c_libraries/homotopy_sse.o' is up to date.
scons: `storm_analysis/c_libraries/homotopy_storm.o' is up to date.
scons: `storm_analysis/c_libraries/libhomotopy_general.so' is up to date.
gcc -o storm_analysis/c_libraries/libhomotopy_ia_sse.so -Wl,-z,defs -shared storm_analysis/c_libraries/homotopy_imagea.o storm_analysis/c_libraries/homotopy_sse.o storm_analysis/c_libraries/homotopy_imagea_common.o storm_analysis/c_libraries/homotopy_common.o -llapack -lrt -lm
/usr/bin/ld: storm_analysis/c_libraries/homotopy_imagea_common.o:(.bss+0x10): multiple definition of `hres_fp'; storm_analysis/c_libraries/homotopy_imagea.o:(.bss+0x10): first defined here
/usr/bin/ld: storm_analysis/c_libraries/homotopy_imagea_common.o:(.bss+0x8): multiple definition of `xvec'; storm_analysis/c_libraries/homotopy_imagea.o:(.bss+0x8): first defined here
/usr/bin/ld: storm_analysis/c_libraries/homotopy_imagea_common.o:(.bss+0x0): multiple definition of `yvec'; storm_analysis/c_libraries/homotopy_imagea.o:(.bss+0x0): first defined here
/usr/bin/ld: storm_analysis/c_libraries/homotopy_imagea_common.o:(.bss+0x28): multiple definition of `hres_x'; storm_analysis/c_libraries/homotopy_imagea.o:(.bss+0x28): first defined here
/usr/bin/ld: storm_analysis/c_libraries/homotopy_imagea_common.o:(.bss+0x24): multiple definition of `hres_y'; storm_analysis/c_libraries/homotopy_imagea.o:(.bss+0x24): first defined here
/usr/bin/ld: storm_analysis/c_libraries/homotopy_imagea_common.o:(.bss+0x20): multiple definition of `scale'; storm_analysis/c_libraries/homotopy_imagea.o:(.bss+0x20): first defined here
/usr/bin/ld: storm_analysis/c_libraries/homotopy_imagea_common.o:(.bss+0x18): multiple definition of `epsilon'; storm_analysis/c_libraries/homotopy_imagea.o:(.bss+0x18): first defined here
collect2: error: ld returned 1 exit status
scons: *** [storm_analysis/c_libraries/libhomotopy_ia_sse.so] Error 1
scons: building terminated because of errors.
Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    'Programming Language :: Python :: 3.6',
  File "/opt/miniconda3/envs/smdm/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/opt/miniconda3/envs/smdm/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/miniconda3/envs/smdm/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/miniconda3/envs/smdm/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 53, in run
    subprocess.check_call(command)
  File "/opt/miniconda3/envs/smdm/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['scons']' returned non-zero exit status 2.

**Comment by HazenBabcock** [comment]
Looks like the C compiler / linker has gotten more picky. I think I have fixed this. Can you try again with the latest git head?

I tested on the same OS, but with Python 3.10. It looks like you are using 3.6? I tried to fix a number of warnings I was seeing in the tests due to changes in numpy, scipy and tifffile, but if you have different (older?) versions of these libraries then I might have broken things for you.

**Comment by MembraneEnzymology** [comment]
Thank you for your quick reply! After a git pull everything went fine. Thank you!

I also tested this with Python 3.10 and this also seems to works fine. I've installed the FFTW3 and LAPACK libraries via the package manager (sudo apt-get install libblas-dev liblapack-dev) . The needed Python packages I've installed via pip (pip install numpy scipy matplotlib pillow tifffile Shapely randomcolor PyWavelets PyQt5 h5py astropy).

~/storm-analysis# git pull
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 48 (delta 37), reused 47 (delta 36), pack-reused 0
Unpacking objects: 100% (48/48), 8.50 KiB | 1.06 MiB/s, done.
From https://github.com/ZhuangLab/storm-analysis
   71ae493c..f0bbda4a  master     -> origin/master
Updating 71ae493c..f0bbda4a
Fast-forward
 appveyor.yml                                          |  4 ++--
 setup.py                                              |  8 ++++----
 storm_analysis/L1H/homotopy_common.h                  |  5 +++++
 storm_analysis/L1H/homotopy_gpu.h                     |  4 ++++
 storm_analysis/L1H/homotopy_imagea_common.h           | 18 +++++++++++-------
 storm_analysis/L1H/homotopy_psf.py                    |  6 +++---
 storm_analysis/L1H/homotopy_storm.h                   |  5 +++++
 storm_analysis/dbscan/clusters_sa_h5py.py             |  8 ++++----
 storm_analysis/rolling_ball_bgr/rolling_ball_lib_c.py |  4 ++--
 storm_analysis/sa_library/datareader.py               |  2 +-
 storm_analysis/sa_library/datawriter.py               |  2 +-
 storm_analysis/sa_library/gaussfit.py                 |  2 +-
 storm_analysis/sa_library/ia_utilities_c.py           |  2 +-
 storm_analysis/sa_library/sa_h5py.py                  |  2 +-
 storm_analysis/spliner/measure_psf.py                 |  4 ++--
 storm_analysis/spliner/measure_psf_utils.py           |  8 ++++----
 storm_analysis/test/test_clusters_sa_h5py.py          | 38 +++++++++++++++++++-------------------
 storm_analysis/test/test_dataio.py                    |  4 ++--
 storm_analysis/test/test_measure_psf_utils.py         | 20 ++++++++++----------
 storm_analysis/test/test_mp_analysis_io.py            | 12 ++++++------
 storm_analysis/test/test_scmos_cal.py                 |  2 +-
 21 files changed, 89 insertions(+), 71 deletions(-)
(smdm) root@scrapmetal:~/storm-analysis# ll
total 104
drwxr-xr-x 10 root     root      4096 nov 22 11:49 ./
drwx------  8 root     root      4096 nov 22 11:48 ../
-rw-r--r--  1 root     root      1692 nov 22 11:49 appveyor.yml
drwxr-xr-x  3 root     root      4096 nov 21 15:30 doc/
drwxr-xr-x  7 root     root      4096 nov 21 15:30 docker/
drwxr-xr-x  4 root     root      4096 nov 21 15:53 .eggs/
drwxr-xr-x  8 root     root      4096 nov 22 11:49 .git/
-rw-r--r--  1 root     root      2587 nov 21 15:30 .gitignore
drwxr-xr-x  3 root     root      4096 nov 21 15:30 imagej_plugins/
drwxr-xr-x  2 root     root      4096 nov 21 15:30 jupyter_notebooks/
-rw-r--r--  1 root     root       588 nov 21 15:30 MANIFEST.in
-rw-r--r--  1 root     root      2773 nov 21 15:30 README.md
-rw-r--r--  1 cmpunter cmpunter 13415 nov 21 16:19 .sconsign.dblite
-rw-r--r--  1 root     root     18249 nov 21 15:30 SConstruct
-rw-r--r--  1 root     root        61 nov 21 15:30 setup.cfg
-rw-r--r--  1 root     root      2570 nov 22 11:49 setup.py
drwxr-xr-x 30 root     root      4096 nov 22 11:29 storm_analysis/
drwxr-xr-x  2 root     root      4096 nov 21 15:30 .travis/
-rw-r--r--  1 root     root       689 nov 21 15:30 .travis.yml
(smdm) root@scrapmetal:~/storm-analysis# vi README.md
(smdm) root@scrapmetal:~/storm-analysis# python setup.py build_c
running build_c
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `storm_analysis/c_libraries/ft_math.o' is up to date.
scons: `storm_analysis/c_libraries/libadmm_lasso.so' is up to date.
scons: `storm_analysis/c_libraries/kdtree.o' is up to date.
scons: `storm_analysis/c_libraries/libdbscan.so' is up to date.
scons: `storm_analysis/c_libraries/libdensestorm.so' is up to date.
scons: `storm_analysis/c_libraries/libfista_fft.so' is up to date.
scons: `storm_analysis/c_libraries/libfrc.so' is up to date.
gcc -o storm_analysis/c_libraries/homotopy_common.o -c -O3 -Wall -fPIC storm_analysis/L1H/homotopy_common.c
gcc -o storm_analysis/c_libraries/homotopy_imagea.o -c -O3 -Wall -fPIC storm_analysis/L1H/homotopy_imagea.c
In file included from storm_analysis/L1H/homotopy_imagea.c:21:
storm_analysis/L1H/homotopy_imagea_common.h:29:14: warning: ‘hres_fp’ defined but not used [-Wunused-variable]
   29 | static FILE *hres_fp;
      |              ^~~~~~~
gcc -o storm_analysis/c_libraries/homotopy_imagea_common.o -c -O3 -Wall -fPIC storm_analysis/L1H/homotopy_imagea_common.c
storm_analysis/L1H/homotopy_imagea_common.c: In function ‘openFile’:
storm_analysis/L1H/homotopy_imagea_common.c:119:5: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  119 |     fread(&last_frame, sizeof(int), 1, hres_fp);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from storm_analysis/L1H/homotopy_imagea_common.c:14:
At top level:
storm_analysis/L1H/homotopy_imagea_common.h:27:15: warning: ‘epsilon’ defined but not used [-Wunused-variable]
   27 | static double epsilon;
      |               ^~~~~~~
gcc -o storm_analysis/c_libraries/homotopy_sse.o -c -O3 -Wall -fPIC storm_analysis/L1H/homotopy_sse.c
storm_analysis/L1H/homotopy_sse.c: In function ‘computeC’:
storm_analysis/L1H/homotopy_sse.c:170:17: warning: ‘temp_v’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  170 |       temp_v[j] = temp;
      |       ~~~~~~~~~~^~~~~~
storm_analysis/L1H/homotopy_sse.c: In function ‘computeG1’:
storm_analysis/L1H/homotopy_sse.c:324:19: warning: ‘temp_v’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  324 |         temp_v[j] = d_vec[i];
      |         ~~~~~~~~~~^~~~~~~~~~
storm_analysis/L1H/homotopy_sse.c: In function ‘l2Error’:
storm_analysis/L1H/homotopy_sse.c:606:17: warning: ‘temp_v’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  606 |       temp_v[j] = temp;
      |       ~~~~~~~~~~^~~~~~
storm_analysis/L1H/homotopy_sse.c: In function ‘newYVector’:
storm_analysis/L1H/homotopy_sse.c:664:17: warning: ‘temp_v’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  664 |       temp_v[j] = 0.0;
      |       ~~~~~~~~~~^~~~~
gcc -o storm_analysis/c_libraries/homotopy_storm.o -c -O3 -Wall -fPIC storm_analysis/L1H/homotopy_storm.c
gcc -o storm_analysis/L1H/homotopy_general.os -c -O3 -Wall -fPIC storm_analysis/L1H/homotopy_general.c
scons: `storm_analysis/c_libraries/libhomotopy_general.so' is up to date.
gcc -o storm_analysis/c_libraries/libhomotopy_ia_sse.so -Wl,-z,defs -shared storm_analysis/c_libraries/homotopy_imagea.o storm_analysis/c_libraries/homotopy_sse.o storm_analysis/c_libraries/homotopy_imagea_common.o storm_analysis/c_libraries/homotopy_common.o -llapack -lrt -lm
gcc -o storm_analysis/c_libraries/libhomotopy_ia_storm.so -Wl,-z,defs -shared storm_analysis/c_libraries/homotopy_imagea.o storm_analysis/c_libraries/homotopy_storm.o storm_analysis/c_libraries/homotopy_imagea_common.o storm_analysis/c_libraries/homotopy_common.o -llapack -lrt -lm
gcc -o storm_analysis/c_libraries/libhomotopy_sse.so -Wl,-z,defs -shared storm_analysis/c_libraries/homotopy_sse.o storm_analysis/c_libraries/homotopy_common.o -llapack -lrt -lm
gcc -o storm_analysis/c_libraries/libhomotopy_storm.so -Wl,-z,defs -shared storm_analysis/c_libraries/homotopy_storm.o storm_analysis/c_libraries/homotopy_common.o -llapack -lrt -lm
gcc -o storm_analysis/c_libraries/mp_fit.o -c -O3 -Wall -fPIC storm_analysis/multi_plane/mp_fit.c
gcc -o storm_analysis/c_libraries/mp_fit_dao.o -c -O3 -Wall -fPIC storm_analysis/multi_plane/mp_fit_dao.c
gcc -o storm_analysis/c_libraries/dao_fit.o -c -O3 -Wall -fPIC storm_analysis/sa_library/dao_fit.c
gcc -o storm_analysis/c_libraries/multi_fit.o -c -O3 -Wall -fPIC storm_analysis/sa_library/multi_fit.c
gcc -o storm_analysis/c_libraries/libmp_fit_dao.so -Wl,-z,defs -shared storm_analysis/c_libraries/dao_fit.o storm_analysis/c_libraries/mp_fit.o storm_analysis/c_libraries/mp_fit_dao.o storm_analysis/c_libraries/multi_fit.o -lfftw3 -llapack -lm
gcc -o storm_analysis/c_libraries/mp_fit_arb.o -c -O3 -Wall -fPIC storm_analysis/multi_plane/mp_fit_arb.c
gcc -o storm_analysis/c_libraries/cubic_fit.o -c -O3 -Wall -fPIC storm_analysis/spliner/cubic_fit.c
gcc -o storm_analysis/c_libraries/cubic_spline.o -c -O3 -Wall -fPIC storm_analysis/spliner/cubic_spline.c
gcc -o storm_analysis/c_libraries/fft_fit.o -c -O3 -Wall -fPIC storm_analysis/psf_fft/fft_fit.c
gcc -o storm_analysis/c_libraries/psf_fft.o -c -O3 -Wall -fPIC storm_analysis/psf_fft/psf_fft.c
gcc -o storm_analysis/c_libraries/pupil_fit.o -c -O3 -Wall -fPIC storm_analysis/pupilfn/pupil_fit.c
gcc -o storm_analysis/c_libraries/pupil_function.o -c -O3 -Wall -fPIC storm_analysis/pupilfn/pupil_function.c
gcc -o storm_analysis/c_libraries/libmp_fit_arb.so -Wl,-z,defs -shared storm_analysis/c_libraries/cubic_fit.o storm_analysis/c_libraries/cubic_spline.o storm_analysis/c_libraries/fft_fit.o storm_analysis/c_libraries/psf_fft.o storm_analysis/c_libraries/pupil_fit.o storm_analysis/c_libraries/pupil_function.o storm_analysis/c_libraries/mp_fit.o storm_analysis/c_libraries/mp_fit_arb.o storm_analysis/c_libraries/multi_fit.o -lfftw3 -llapack -lm
gcc -o storm_analysis/c_libraries/libpsf_fft.so -Wl,-z,defs -shared storm_analysis/c_libraries/psf_fft.o -lfftw3 -lm
gcc -o storm_analysis/c_libraries/libfft_fit.so -Wl,-z,defs -shared storm_analysis/c_libraries/multi_fit.o storm_analysis/c_libraries/psf_fft.o storm_analysis/c_libraries/fft_fit.o -lfftw3 -llapack -lm
gcc -o storm_analysis/c_libraries/otf_scaling.o -c -O3 -Wall -fPIC storm_analysis/pupilfn/otf_scaling.c
gcc -o storm_analysis/c_libraries/libotf_scaling.so -Wl,-z,defs -shared storm_analysis/c_libraries/otf_scaling.o -lfftw3 -lm
gcc -o storm_analysis/c_libraries/libpupil_function.so -Wl,-z,defs -shared storm_analysis/c_libraries/pupil_function.o -lfftw3 -lm
gcc -o storm_analysis/c_libraries/libpupil_fit.so -Wl,-z,defs -shared storm_analysis/c_libraries/multi_fit.o storm_analysis/c_libraries/pupil_function.o storm_analysis/c_libraries/pupil_fit.o -lfftw3 -llapack -lm
gcc -o storm_analysis/rolling_ball_bgr/rolling_ball_lib.os -c -O3 -Wall -fPIC storm_analysis/rolling_ball_bgr/rolling_ball_lib.c
gcc -o storm_analysis/c_libraries/librolling_ball_lib.so -Wl,-z,defs -shared storm_analysis/rolling_ball_bgr/rolling_ball_lib.os
gcc -o storm_analysis/c_libraries/libdao_fit.so -Wl,-z,defs -shared storm_analysis/c_libraries/dao_fit.o storm_analysis/c_libraries/multi_fit.o -llapack -lm
gcc -o storm_analysis/sa_library/affine_transform.os -c -O3 -Wall -fPIC storm_analysis/sa_library/affine_transform.c
gcc -o storm_analysis/c_libraries/libaffine_transform.so -Wl,-z,defs -shared storm_analysis/sa_library/affine_transform.os
gcc -o storm_analysis/sa_library/cs_decon_utilities.os -c -O3 -Wall -fPIC storm_analysis/sa_library/cs_decon_utilities.c
gcc -o storm_analysis/c_libraries/libcs_decon_utilities.so -Wl,-z,defs -shared storm_analysis/sa_library/cs_decon_utilities.os
gcc -o storm_analysis/sa_library/grid.os -c -O3 -Wall -fPIC storm_analysis/sa_library/grid.c
gcc -o storm_analysis/c_libraries/libgrid.so -Wl,-z,defs -shared storm_analysis/sa_library/grid.os
gcc -o storm_analysis/sa_library/ia_utilities.os -c -O3 -Wall -fPIC storm_analysis/sa_library/ia_utilities.c
gcc -o storm_analysis/c_libraries/libia_utilities.so -Wl,-z,defs -shared storm_analysis/c_libraries/kdtree.o storm_analysis/sa_library/ia_utilities.os -lm
gcc -o storm_analysis/sa_library/matched_filter.os -c -O3 -Wall -fPIC storm_analysis/sa_library/matched_filter.c
gcc -o storm_analysis/c_libraries/libmatched_filter.so -Wl,-z,defs -shared storm_analysis/c_libraries/ft_math.o storm_analysis/sa_library/matched_filter.os -lfftw3
gcc -o storm_analysis/sa_utilities/fitz.os -c -O3 -Wall -fPIC storm_analysis/sa_utilities/fitz.c
gcc -o storm_analysis/c_libraries/libfitz.so -Wl,-z,defs -shared storm_analysis/sa_utilities/fitz.os -lm
gcc -o storm_analysis/simulator/draw_gaussians.os -c -O3 -Wall -fPIC storm_analysis/simulator/draw_gaussians.c
gcc -o storm_analysis/c_libraries/libdraw_gaussians.so -Wl,-z,defs -shared storm_analysis/simulator/draw_gaussians.os -lm
gcc -o storm_analysis/simulator/pf_math.os -c -O3 -Wall -fPIC storm_analysis/simulator/pf_math.c
gcc -o storm_analysis/c_libraries/libpf_math.so -Wl,-z,defs -shared storm_analysis/simulator/pf_math.os -lfftw3 -lm
gcc -o storm_analysis/c_libraries/libcubic_spline.so -Wl,-z,defs -shared storm_analysis/c_libraries/cubic_spline.o
gcc -o storm_analysis/c_libraries/libcubic_fit.so -Wl,-z,defs -shared storm_analysis/c_libraries/cubic_fit.o storm_analysis/c_libraries/cubic_spline.o storm_analysis/c_libraries/multi_fit.o -llapack -lm
scons: done building targets.
(smdm) root@scrapmetal:~/storm-analysis# python setup.py install
running install
running bdist_egg
running egg_info
creating storm_analysis.egg-info
writing storm_analysis.egg-info/PKG-INFO
writing dependency_links to storm_analysis.egg-info/dependency_links.txt
writing top-level names to storm_analysis.egg-info/top_level.txt
writing manifest file 'storm_analysis.egg-info/SOURCES.txt'
