### ISSUE TITLE
OSError during z fitting

### ISSUE THREAD

**Issue by Z-Qing** [ZhuangLab/storm-analysis#48]
HI, I installed strom-analysis using anaconda on win11. The dao3d_zcal.ipynb runs fine. But when I use my own data, the fitting z process failed and I got the following message. Could anyone help me out? Thanks.

OSError                                   Traceback (most recent call last)
Cell In [7], line 4
      1 if os.path.exists("measure.hdf5"):
      2     os.remove("measure.hdf5")
----> 4 mfit.analyze("P1.tif", "measure.hdf5", "measure.xml")

File D:\Anaconda3\envs\stan\lib\site-packages\storm_analysis-2.2-py3.10.egg\storm_analysis\daostorm_3d\mufit_analysis.py:42, in analyze(movie_name, mlist_name, settings_name)
     37 data_writer = analysisIO.DataWriterHDF5(data_file = mlist_name,
     38                                         parameters = parameters,
     39                                         sa_type = '3D-DAOSTORM')
     41 # Run the analysis.
---> 42 std_analysis.standardAnalysis(finder,
     43                               movie_reader,
     44                               data_writer,
     45                               parameters)

File D:\Anaconda3\envs\stan\lib\site-packages\storm_analysis-2.2-py3.10.egg\storm_analysis\sa_utilities\std_analysis.py:125, in standardAnalysis(find_peaks, movie_reader, data_writer, parameters)
    120 print("Peak finding")
    121 if peakFinding(find_peaks, movie_reader, data_writer, parameters):
    122 
    123     # Do drift correction, tracking, and zfit (for '3d' model).
    124     #
--> 125     trackDriftCorrect(data_writer.getFilename(),
    126                       parameters)
    128     # Perform requested file format conversions.
    129     #
    130     convert(data_writer.getFilename(), parameters)

File D:\Anaconda3\envs\stan\lib\site-packages\storm_analysis-2.2-py3.10.egg\storm_analysis\sa_utilities\std_analysis.py:147, in trackDriftCorrect(h5_name, parameters)
    145         print()
    146         print("'3d' localization z fitting.")
--> 147         zFitting(h5_name, parameters, False)
    149 # Drift correction.
    150 #
    151 if (parameters.getAttr("drift_correction", 0) != 0):

File D:\Anaconda3\envs\stan\lib\site-packages\storm_analysis-2.2-py3.10.egg\storm_analysis\sa_utilities\std_analysis.py:226, in zFitting(h5_name, parameters, fit_tracks)
    218     fitzC.fitzTracks(h5_name,
    219                      parameters.getAttr("cutoff"),
    220                      wx_params,
   (...)
    223                      max_z,
    224                      z_step)
    225 else:
--> 226     fitzC.fitzRaw(h5_name,
    227                   parameters.getAttr("cutoff"),
    228                   wx_params,
    229                   wy_params,
    230                   min_z,
    231                   max_z,
    232                   z_step)

File D:\Anaconda3\envs\stan\lib\site-packages\storm_analysis-2.2-py3.10.egg\storm_analysis\sa_utilities\fitz_c.py:101, in fitzRaw(h5_name, cutoff, wx_params, wy_params, z_min, z_max, z_step, wx_wy_fields)
     99             wx = pixel_size * 2.0 * locs[wx_field][i]
    100             wy = pixel_size * 2.0 * locs[wy_field][i]
--> 101             z_vals[i] = c_fitz.findBestZ(zfit_data, wx, wy) * 1.0e-3
    102         h5.addLocalizationZ(z_vals, fnum)
    104 c_fitz.cleanup(zfit_data)

OSError: exception: access violation reading 0x0000000000000000

**Comment by HazenBabcock** [comment]
Can you share "P1.tif" and "measure.xml" somewhere like Google drive?

**Comment by HazenBabcock** [comment]
It looks like the problem is that min_z (0.2) is greater than max_z (-0.2) in your XML file. The analysis is not designed to handle this, it expects min_z to be less than max_z.

**Comment by Z-Qing** [comment]
Thank you. It works now.

**Comment by HazenBabcock** [comment]
I think is resolved.
