### ISSUE TITLE
Region of interest misbehaving

### ISSUE THREAD

**Issue by BogdanBintu** [ZhuangLab/storm-analysis#5]
The region of interest specified in the parameters files via:

	<x_start type="int">30</x_start>
	<x_stop type="int">200</x_stop>
	<y_start type="int">30</y_start>
	<y_stop type="int">200</y_stop>
`
did not perform as expected.
Fix:
In **storm-analysis\sa_library\fitting.py**
starting with **line 207**:

        if self.peak_mask is None:
            parameters = self.parameters
            self.peak_mask = numpy.ones(new_image.shape)
            margin = 10
            if hasattr(parameters, "x_start"):
                self.peak_mask[margin:parameters.x_start+margin,:] = 0.0
            if hasattr(parameters, "x_stop"):
                self.peak_mask[margin+parameters.x_stop:-1,:] = 0.0
            if hasattr(parameters, "y_start"):
                self.peak_mask[:,margin:parameters.y_start+margin] = 0.0
            if hasattr(parameters, "y_stop"):
                self.peak_mask[:,margin+parameters.y_stop:-1] = 0.0
`

**Comment by HazenBabcock** [comment]
This should be fixed now. Thank you for reporting this problem.
