### ISSUE TITLE
fitz z range is hard coded

### ISSUE THREAD

**Issue by HazenBabcock** [ZhuangLab/storm-analysis#7]
The range of z values that the fitz function covers (used for 3D-DAOSTORM 3D zfit) is hard coded to +-500nm. This should be an input parameter.

**Comment by evanheller** [comment]
Is this true? It looks like it gets the z range from the parameters file.

**Comment by HazenBabcock** [comment]
It is true for "3d" fit mode, but not "z" fit mode. In "3d" mode the width in x and y are fit independently and then the z position is determined from the x, y vs z calibration curve. In "z" fit mode the x and y width are fit as a single parameter z, they are not allowed to vary independently.

**Comment by HazenBabcock** [comment]
This should be fixed now.
